// Arduino helpers for CONFIG_ entries
#ifndef CONFIG_BUTTON_MAX
#define CONFIG_BUTTON_MAX 5
#endif

#ifndef CONFIG_BUTTON_POLL_TIMEOUT
#define CONFIG_BUTTON_POLL_TIMEOUT 10
#endif

#ifndef CONFIG_BUTTON_LONG_PRESS_TIMEOUT
#define CONFIG_BUTTON_LONG_PRESS_TIMEOUT 1000
#endif

#ifndef CONFIG_BUTTON_AUTOREPEAT_TIMEOUT
#define CONFIG_BUTTON_AUTOREPEAT_TIMEOUT 500
#endif

#ifndef CONFIG_BUTTON_AUTOREPEAT_INTERVAL
#define CONFIG_BUTTON_AUTOREPEAT_INTERVAL 250
#endif

#ifndef LED_STRIP_SPI_USING_SK9822
#define LED_STRIP_SPI_USING_SK9822 1
#endif

#ifndef CONFIG_LED_STRIP_SPI_MUTEX_TIMEOUT_MS
#define CONFIG_LED_STRIP_SPI_MUTEX_TIMEOUT_MS 1
#endif

#ifndef CONFIG_ONEWIRE_CRC8_TABLE
#define CONFIG_ONEWIRE_CRC8_TABLE "y"
#endif

#ifndef CONFIG_LED_STRIP_FLUSH_TIMEOUT
#define CONFIG_LED_STRIP_FLUSH_TIMEOUT 1000
#endif

#ifndef CONFIG_I2CDEV_TIMEOUT
#define CONFIG_I2CDEV_TIMEOUT 1000
#endif

#ifndef CONFIG_I2CDEV_NOLOCK
#define CONFIG_I2CDEV_NOLOCK n
#endif

#ifndef CONFIG_HMC5883L_MEAS_TIMEOUT
#define CONFIG_HMC5883L_MEAS_TIMEOUT 6000
#endif

#ifndef CONFIG_RE_MAX
#define CONFIG_RE_MAX 1
#endif

#ifndef CONFIG_RE_INTERVAL_US
#define CONFIG_RE_INTERVAL_US 1000
#endif

#ifndef CONFIG_RE_BTN_DEAD_TIME_US
#define CONFIG_RE_BTN_DEAD_TIME_US 10000
#endif

#ifndef CONFIG_RE_BTN_LONG_PRESS_TIME_US
#define CONFIG_RE_BTN_LONG_PRESS_TIME_US 500000
#endif

#ifndef CONFIG_EXAMPLE_NUMBER
#define CONFIG_EXAMPLE_NUMBER 1
#endif

